Do not honor string power levels
matrix-org/matrix-js-sdk pull request #1754
Opened 2021-06-23 03:39 UTC by aaronraimist

Requires

2021-06-23 13:47 UTC, jryans requested changes
Thanks, seems reasonable overall, but would be good to use the same checks in all power level paths.

2021-06-23 13:47 UTC, jryans commented on src/models/room-member.ts
> +        if (users[this.userId] !== undefined && Number.isInteger(users[this.userId])) {
I noticed we also have related but different checks in `room-state.ts` as part of `maySendEventOfType`, where `Number.isFinite` is used... Perhaps those should also require integers as well?

2021-06-29 03:47 UTC, aaronraimist commented
I'm not sure where else you want changed. As far as I can tell this is the only place Element uses the JS SDK to show a PL.

These string power levels aren't going to last a much longer anyway since I also made a PR to enforce integers in Synapse https://github.com/matrix-org/synapse/pull/10232 so I don't think it's worth putting a whole lot more time in on the client side.

2021-06-30 15:39 UTC, jryans approved these changes
That's all I had in mind, thanks. Just seems good to have similar checks all around.

2021-06-30 15:39 UTC, merged