Convert SearchResult, InteractiveAuth, PushProcessor and Scheduler to TS
matrix-org/matrix-js-sdk pull request #1772
Opened 2021-07-07 10:10 UTC by t3chguy

2021-08-10 09:48 UTC, t3chguy commented
Blocked until after RC

2021-08-11 20:23 UTC, turt2live requested changes

2021-08-11 20:23 UTC, turt2live commented on src/@types/PushRules.ts
> +export type PushRuleCondition = IEventMatchCondition
custom conditions are still possible though?

2021-08-11 20:23 UTC, turt2live commented on src/interactive-auth.ts
> +        (err as any).available_flows = flows;
we should type the error, or at least leave comments about the cast. `// TODO: Types` is fine imo

2021-08-11 20:23 UTC, turt2live commented on src/pushprocessor.ts
> +interface IRuleset {
type already exists as `PushRuleSet`.

2021-08-11 20:23 UTC, turt2live commented on src/pushprocessor.ts
> +export interface IRulesets {
type already exists

2021-08-11 20:23 UTC, turt2live commented on src/pushprocessor.ts
> +    public static actionListToActionsObject(actionList: PushRuleAction[]): IActionsObject {
please can we put static functions below the constructor :(

2021-08-11 20:23 UTC, turt2live commented on src/scheduler.ts
> +}
one day we should just use the logging library directly.

2021-08-11 20:24 UTC, turt2live commented
gah, pressed buttons too quickly: overall the first readthrough of the diff looks fine. It's large enough where there's probably going to be a second read on re-review and a small chance of a third.

2021-08-11 20:37 UTC, turt2live commented on src/@types/PushRules.ts
> +export type PushRuleCondition = IEventMatchCondition
discussed oob: removing this type makes life easier down the road, and realistically we don't care about custom conditions at this layer. Would be fine with a comment acknowledging this.

2021-08-13 15:51 UTC, t3chguy commented
@turt2live please merge after approval along with https://github.com/matrix-org/matrix-react-sdk/pull/6323 - I will be on holiday

2021-08-13 16:08 UTC, turt2live approved these changes

2021-08-13 16:08 UTC, merged