Add support for stopping and resuming sync loop from client
matrix-org/matrix-js-sdk pull request #1999
Opened 2021-10-25 09:44 UTC by arthurthouzeau

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/1996

It is currently not possible for consumers of the client to pause the sync loop and resume it a bit later from where it was stopped. This PR exposes methods on the client to pause and resume the sync loop.

---
Here's what your changelog entry will look like:

## ✨ Features
 * Add support for stopping and resuming sync loop from client. ([\#1999](https://github.com/matrix-org/matrix-js-sdk/pull/1999)). Fixes #1996. Contributed by @arthurthouzeau.

2021-11-01 16:52 UTC, arthurthouzeau commented
Hey,

Would anyone from the team be able to review this change?

Thanks!

2021-11-11 10:34 UTC, arthurthouzeau commented
Hi @gsouquet 

Would you be able to review this change?

Thanks a lot for your help

2022-01-07 16:09 UTC, arthurthouzeau commented
Hey there, happy new year! 

Would anyone be able to review this change?

Thanks

2022-01-19 10:32 UTC, arthurthouzeau commented
Hey @turt2live, 

Sorry to ping again. Is there a specific process to follow to get a PR reviewed for matrix-js-sdk? I've had this one open for nearly 3 months now and didn't manage to a get any review yet, so wondering what I should do. I unfortunately need this change to be able to upgrade.

Thanks a lot for your help
Arthur

2022-04-09 04:27 UTC, turt2live requested changes
Apologies for the long review cycle on this - PRs from community members unfortunately take longer than they should.

Generally I'm not sure this is a change the SDK would be able to support - we design the whole thing around the idea of starting or stopping the whole client, not necessarily pausing the sync loop specifically. Are you potentially looking for a lighter weight SDK which does support this and don't need all the other functionality a MatrixClient provides?

2022-04-09 04:27 UTC, turt2live commented on src/client.ts
> +    }
SDK-wise, I'm not sure we want to support a "start sync" function - the consumer should be starting the whole client instance, not just sync.

2022-04-09 04:27 UTC, turt2live commented on src/client.ts
> +    }
similarly, we have a `stopClient` function already.

2022-08-04 13:23 UTC, closed without merging