Converting src/browser-index.js to typescript
matrix-org/matrix-js-sdk pull request #2016
Opened 2021-11-09 18:56 UTC by Aryaman1706

Signed-off-by:  Aryaman Grover <1761ary@gmail.com>

2021-11-09 19:10 UTC, Aryaman1706 commented
Hello all!
I am having a look at failing tests and would fix soon.

2021-11-10 06:53 UTC, Aryaman1706 commented
@SimonBrandner Can you please have a look and let me know if anything else is required. 
Thank You.

2021-11-10 07:07 UTC, SimonBrandner reviewed
Thanks for working on this! 

I am not the most knowledgeable about this part of the app, so better to leave the review to someone else. A review from a team member is required anyway

2021-11-10 09:00 UTC, Aryaman1706 commented
@SimonBrandner Thank you for the response.
Can you let me know who all are the active maintainers so that I could tag them and ask for the review?

2021-11-10 09:02 UTC, SimonBrandner commented
> Can you let me know who all are the active maintainers so that I could tag them and ask for the review?

A review from them has already been requested. You can see review requests in the top right corner

2021-11-12 06:41 UTC, Aryaman1706 commented
@dbkr Kindly have a look please.
Let me know if any further changes are required.

2021-12-28 20:46 UTC, turt2live requested changes
Overall it seems fine - thanks! There's a few pieces to fix up here, and some merge conflicts to consider.

2021-12-28 20:46 UTC, turt2live commented on src/browser-index.ts
> +}
This should be a constant

2021-12-28 20:46 UTC, turt2live commented on src/browser-index.ts
> +type GlobalObject = NodeJS.Global & typeof globalThis & Record<"matrixcs", typeof matrixcs>;
I thought we already had a type for this? In general I don't think we should be touching `global` and should fix it.

2021-12-28 20:46 UTC, turt2live commented on src/browser-index.ts
> +}
we should be importing this type, not defining it.

2022-05-10 19:15 UTC, t3chguy commented
@Aryaman1706 are you able to continue with this PR?

2023-07-06 12:39 UTC, t3chguy commented
This happened

2023-07-06 12:39 UTC, closed without merging