Add type
matrix-org/matrix-js-sdk pull request #2023
Opened 2021-11-17 09:43 UTC by skyka13711

2021-11-19 01:35 UTC, turt2live requested changes
Thanks for the contribution! It would be great if we can get a more complete title for this PR so it shows up in the changelog correctly, and it looks like the `yarn.lock` was accidentally committed with no relevant `package.json` changes.

2021-11-19 01:35 UTC, turt2live commented on src/index.ts
> +export { EventType } from './@types/event';
we should probably be using `export *` for all of these.

2021-11-25 18:06 UTC, skyka13711 commented
fixed

2021-11-30 02:54 UTC, turt2live approved these changes
Thanks!

2021-11-30 02:54 UTC, merged