Typescriptify crypto integration tests
matrix-org/matrix-js-sdk pull request #2508
Opened 2022-07-08 22:41 UTC by duxovni

2022-07-08 22:42 UTC, duxovni commented
Oh right, I was working on top of #2505, I'll merge in develop once that gets merged and that should fix the type errors.

2022-07-08 22:48 UTC, turt2live requested changes
overall looks good - thank you! Mostly just need to add a bunch of return types :)

2022-07-08 22:48 UTC, turt2live commented on spec/integ/matrix-client-crypto.spec.ts
>  function bobUploadsDeviceKeys() {
return type

2022-07-08 22:48 UTC, turt2live commented on spec/integ/matrix-client-crypto.spec.ts
>  function bobUploadsDeviceKeys() {
applies throughout to other functions as well (unreachable with line comments)

2022-07-08 22:48 UTC, turt2live commented on spec/integ/matrix-client-crypto.spec.ts
> +    return expectSendMessageRequest(aliTestClient.httpBackend).then(function(content: IContent) {
all these inline functions should probably be converted to arrow functions, but not the end of the world.

2022-07-08 22:48 UTC, turt2live commented on spec/integ/matrix-client-crypto.spec.ts
> +                            event);
I'm surprised `event` is even on its own line?

2022-07-11 20:01 UTC, turt2live approved these changes
lgtm.

For future PRs, it's generally best to break each refactor into its own commit so the review is easier, though in this case it worked out well enough. We end up collapsing the commits down to one at merge, so they're effectively free :D

2022-07-12 16:18 UTC, merged