test typescriptification - spec/integ
matrix-org/matrix-js-sdk pull request #2714
Opened 2022-09-29 14:36 UTC by kerryarchibald

The final instalment of test typescriptification 🥳

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/2353

## Checklist

* [ ] Tests written for new code (and old code if feasible)
* [ ] Linter and other CI checks pass
* [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))

2022-09-29 19:03 UTC, turt2live reviewed
clearing code review while draft

2022-09-30 17:43 UTC, duxovni requested changes
The `expect`s that can be compressed into one line are just a nitpick, mostly focused on the un-cleaned-up `httpBackend`s and the `==`s.

2022-09-30 17:43 UTC, duxovni commented on spec/integ/devicelist-integ.spec.ts
> +                    0,
May as well just make this a single line

2022-09-30 17:43 UTC, duxovni commented on spec/integ/devicelist-integ.spec.ts
> +                    0,
Likewise

2022-09-30 17:43 UTC, duxovni commented on spec/integ/devicelist-integ.spec.ts
> +                    0,
^

2022-09-30 17:43 UTC, duxovni commented on spec/integ/devicelist-integ.spec.ts
> +                        0,
^

2022-09-30 17:43 UTC, duxovni commented on spec/integ/matrix-client-event-emitter.spec.ts
> +        [client, httpBackend] = setupTests();
Is there a way of doing this that doesn't leave a running httpBackend lying around?

2022-09-30 17:43 UTC, duxovni commented on spec/integ/matrix-client-methods.spec.ts
> +        [client, httpBackend, store] = setupTests();
Here as well

2022-09-30 17:43 UTC, duxovni commented on spec/integ/matrix-client-methods.spec.ts
>                          req.headers["Authorization"] == "Bearer " + accessToken)) {
These should be `===` right?

2022-09-30 17:43 UTC, duxovni commented on spec/integ/matrix-client-opts.spec.ts
>                  );
This can also be a one-liner now

2022-09-30 17:43 UTC, duxovni commented on spec/integ/matrix-client-opts.spec.ts
>              );
And here

2022-09-30 17:43 UTC, duxovni commented on spec/integ/matrix-client-retrying.spec.ts
>      });
Loose httpBackend here too

2022-09-30 17:43 UTC, duxovni commented on spec/integ/matrix-client-room-timeline.spec.ts
> +        [client, httpBackend] = setupTestClient();
And here

2022-09-30 17:43 UTC, duxovni commented on spec/integ/matrix-client-syncing.spec.ts
> +        [client, httpBackend] = setupTestClient();
And here

2022-10-06 05:04 UTC, duxovni approved these changes
Looks good, there's still the `==` here but it's a minor nitpick in the context of a test.

2022-10-06 05:04 UTC, duxovni commented on spec/integ/matrix-client-methods.spec.ts
>                          req.headers["Authorization"] == "Bearer " + accessToken)) {
^

2022-10-06 06:11 UTC, merged