Avoid triggering decryption errors when decrypting redacted events
matrix-org/matrix-js-sdk pull request #3004
Opened 2022-12-21 21:14 UTC by uhoreg

Currently, when processing a redacted event, it tries to decrypt the `redacted_because`  (https://github.com/matrix-org/matrix-js-sdk/pull/1589).  However, since this often is not encrypted, the decryption will fail, and this failure will bubble up to the parent event.  This patch simply uses the plain `redacted_because` if it is unable to decrypt it.

2022-12-22 10:31 UTC, gsouquet requested changes
Otherwise looks good to me

2022-12-22 10:31 UTC, gsouquet commented on spec/unit/crypto.spec.ts
> +        it("doesn't throw an error when attempting to decrypt a redacted event", async () => {
Could we also assess that `redacted_because` is correctly set? That sounds like an important edge to test against

2022-12-22 10:32 UTC, richvdh commented on src/crypto/index.ts
> +            }
I feel like we should make this conditional on `redactionEvent.isEncrypted()`, and log a warning if we find it is encrypted but we can't decrypt.

2022-12-28 08:32 UTC, gsouquet approved these changes

2023-01-03 13:45 UTC, richvdh approved these changes

2023-01-03 16:06 UTC, merged