Stop running jest in parallel
matrix-org/matrix-js-sdk pull request #3517
Opened 2023-06-27 10:24 UTC by richvdh

... it makes the output impossible to understand.

2023-06-27 12:26 UTC, richvdh commented on spec/integ/matrix-client-syncing.spec.ts
> +        await idbClient.store.save(true);
once we limit jest to one worker, it realises that something is logging after shutdown, and complains about it. This makes sure that the test cleans up properly.

2023-06-27 12:46 UTC, t3chguy requested changes
This goes directly against one of the goals of the Web Weekly [Reduce time required to run tests](https://github.com/vector-im/element-web/issues/21971) so needs discussion there

2023-06-27 12:50 UTC, richvdh commented
> This goes directly against one of the goals of the Web Weekly [Reduce time required to run tests](https://github.com/vector-im/element-web/issues/21971) so needs discussion there

I don't think it makes any difference. Compare https://github.com/matrix-org/matrix-js-sdk/actions/runs/5389744563/jobs/9784333178?pr=3517 *with* this PR (1m53s) with https://github.com/matrix-org/matrix-js-sdk/actions/runs/5389733941/jobs/9784477473?pr=3521 without it (1m49s)

2023-06-27 13:18 UTC, t3chguy commented
That's a 3.7% increase in time, which whilst we have few tests is negligible, but if we grow our number of tests we'd end up wanting to revert this, I don't think its the right approach personally. Happy to be overriden. -0 for me

2023-06-29 14:58 UTC, richvdh commented
closing this for now due to general lack of consensus. I may reopen in future if it continues to grind my gears

2023-06-29 14:58 UTC, closed without merging