Valere/rust backup status api
matrix-org/matrix-js-sdk pull request #3555
Opened 2023-07-07 09:12 UTC by BillCarsonFr

#Fixes https://github.com/vector-im/crypto-internal/issues/106

Based on https://github.com/matrix-org/matrix-js-sdk/pull/3548

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))

2023-07-07 09:20 UTC, t3chguy requested changes
![image](https://github.com/matrix-org/matrix-js-sdk/assets/2403652/52836a28-47de-4131-a135-09b2988b149f)

The `#` breaks Github's autoclose behaviour, also please fix the PR title

2023-07-27 20:14 UTC, t3chguy reviewed
Sonar looks unhappy

2023-07-27 22:43 UTC, richvdh commented
Better now

2023-07-27 23:22 UTC, t3chguy approved these changes

2023-07-28 08:16 UTC, merged