Export typed event emitter key types
matrix-org/matrix-js-sdk pull request #3597
Opened 2023-07-12 15:32 UTC by t3chguy

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/3506

2023-07-12 17:28 UTC, richvdh requested changes

2023-07-12 17:28 UTC, richvdh commented on src/matrix.ts
> +export { VerificationRequestEvent, VerifierEvent } from "./crypto-api/verification";
these are already exposed via `export * as Crypto` below (and are documented as such in the jsdoc). Please don't clutter the main namespace more than it has to be.

2023-07-13 10:59 UTC, richvdh commented on src/matrix.ts
> +export { VerificationRequestEvent, VerifierEvent } from "./crypto-api/verification";
The "rule", at least in my head, is that crypto-related stuff should be contained within the `Crypto` namespace. `CryptoEvent` predates my recent work in this area so hasn't (yet) been moved. (And if it was moved, we'd still have to export it at the top level for backwards compat.)

2023-07-13 11:03 UTC, t3chguy commented on src/matrix.ts
> +export { VerificationRequestEvent, VerifierEvent } from "./crypto-api/verification";
```suggestion
```

2023-07-13 11:08 UTC, richvdh approved these changes
thanks!

2023-07-13 11:22 UTC, merged