Fixes around thread root non-thread relations and read receipts
matrix-org/matrix-js-sdk pull request #3607
Opened 2023-07-18 10:48 UTC by t3chguy

Which caused stuck notifications

Review commit-by-commit

2023-07-18 11:04 UTC, andybalaam approved these changes
Looks good, one tiny comment.

2023-07-18 11:04 UTC, andybalaam commented on src/client.ts
> +            thread = bodyOrThread as string | null;
`|` -> `||` ?

2023-07-18 11:04 UTC, andybalaam commented on src/client.ts
> +            thread = bodyOrThread as string | null;
Oh no, ignore me.

2023-07-18 11:07 UTC, t3chguy commented on spec/unit/read-receipt.spec.ts
> +        it("sends an main timeline receipt for a thread root (deprecated)", async () => {
```suggestion
        it("sends a main timeline receipt for a thread root (deprecated)", async () => {
```

2023-07-18 11:07 UTC, t3chguy commented on spec/unit/read-receipt.spec.ts
> +        it("sends an main timeline receipt for a reaction to a thread root (deprecated)", async () => {
```suggestion
        it("sends a main timeline receipt for a reaction to a thread root (deprecated)", async () => {
```

2023-07-19 10:42 UTC, andybalaam requested changes
I just tried this out locally, and edits to thread roots are not reflected until I refresh:

![image](https://github.com/matrix-org/matrix-js-sdk/assets/76812/579be285-0a67-4328-8844-39d1a047a83f)

(Changing to a different room and back did not fix the problem)

Switching back to develop, I see the change immediately.

2023-07-19 10:57 UTC, andybalaam commented
> Screen.Recording.2023-07-19.at.11.46.07.mov
> 
> @andybalaam I cannot reproduce that at all, are you sure your build was fine? I'm using https://pr11294--matrix-react-sdk.netlify.app/

On the netlify build I see the same as you, but when I build locally, with only matrix-js-sdk on `t3chguy/stuck-edits-thread-root` I see the behaviour I described.

I note that there is still a `t3chguy/stuck-edits-thread-root` branch on matrix-react-sdk even though the PR is closed: https://github.com/matrix-org/matrix-react-sdk/pull/11291

Could branch matching be fooling us here?

2023-07-19 11:04 UTC, t3chguy commented
https://pr11294--matrix-react-sdk.netlify.app/ is a build from https://github.com/matrix-org/matrix-react-sdk/pull/11294 not https://github.com/matrix-org/matrix-react-sdk/pull/11291 - the branch was reused between PRs and has since been deleted. Given https://github.com/matrix-org/matrix-react-sdk/pull/11294 only touches cypress I don't see how branch matching could be doing anything awry here. Critically in the screencap I included above you can see the edit hidden event is in the main timeline, unlike on develop where it'd be in the thread timeline:

![image](https://github.com/matrix-org/matrix-js-sdk/assets/2403652/8f384d9f-c781-4b70-9b16-bb54b20b67c9)

2023-07-19 11:12 UTC, andybalaam approved these changes
OK, I just rebuilt locally and it worked fine, so I have no idea what was happening before - I would doubt it happened, except the screenshot shows something.

Good that this is going in now, so we've some time to test before the next RC, but it looks sensible to me, thanks!

2023-07-19 11:38 UTC, merged