Add `CryptoApi.getCrossSigningKeyId`
matrix-org/matrix-js-sdk pull request #3619
Opened 2023-07-25 15:05 UTC by florianduros

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))

2023-07-25 16:23 UTC, richvdh requested changes
There's slightly more to it than this. The api doc for `CryptoApi.getCrossSigningKeyId` says:

> If cross-signing has been initialised on this device, the ID of the given key. Otherwise, null

... which I think means we should call `OlmMachine.crossSigningStatus()` to check that it has been initialised.

And also we should probably call `OwnUserIdentity::is_verified` to check that the  public key matches the private key?

2023-07-25 16:23 UTC, richvdh commented on src/crypto-api.ts
> + * More information https://spec.matrix.org/v1.7/client-server-api/#post_matrixclientv3keysdevice_signingupload
![image](https://github.com/matrix-org/matrix-js-sdk/assets/1389908/eaa97e15-086e-45cb-865f-75cea9d89248)


```suggestion
 *
 * @see https://spec.matrix.org/v1.7/client-server-api/#post_matrixclientv3keysdevice_signingupload
```

2023-07-25 16:34 UTC, florianduros commented
> 



> There's slightly more to it than this. The api doc for `CryptoApi.getCrossSigningKeyId` says:
> 
> > If cross-signing has been initialised on this device, the ID of the given key. Otherwise, null
> 
> ... which I think means we should call `OlmMachine.crossSigningStatus()` to check that it has been initialised.
> 
> And also we should probably call `OwnUserIdentity::is_verified` to check that the public key matches the private key?
Oh, I thought that if we had an `UserIdentity`, it means that the cross signing has been initialized

2023-07-26 15:59 UTC, richvdh approved these changes
It would be nice to have tests for these edge cases, but I guess it's fine for now.

2023-07-26 15:59 UTC, richvdh commented on src/rust-crypto/rust-crypto.ts
>          }
This is a bit hard to follow
```suggestion
        if (!userIdentity || !privateKeysOnDevice) {
            // The public or private keys are not available on this device
            return null;
        }
        
        if (!userIdentity.isVerified()) {
            // We have both public and private keys, but they don't match!
            return null;
        }
```

2023-07-26 15:59 UTC, richvdh commented on spec/integ/crypto/cross-signing.spec.ts
> +            // Intercept cross singing keys upload
:musical_note: 

```suggestion
            // Intercept cross signing keys upload
```

2023-07-26 16:26 UTC, merged