T-Defect: stop keep alive, when sync was stoped
matrix-org/matrix-js-sdk pull request #3720
Opened 2023-09-12 08:59 UTC by finsterwalder

Type: [defect]`T-Defect`
This PR solves issue: https://github.com/matrix-org/matrix-js-sdk/issues/3678

When you start a client, which has connection problems, a keepAlive is started.
But when the connection is actively stopped e.g. via calling stopSync(), the keepAlive is not aborted and keeps retrying possibly indefinitely.

## Checklist

-   [x] Tests written for new code (and old code if feasible)
-   [x] Linter and other CI checks pass
-   [x] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))

2023-09-12 09:57 UTC, t3chguy requested changes

2023-09-12 09:57 UTC, t3chguy commented on spec/integ/matrix-client-syncing-errors.spec.ts
> +Copyright 2022 The Matrix.org Foundation C.I.C.
This is incorrect

2023-09-12 09:59 UTC, finsterwalder commented on spec/integ/matrix-client-syncing-errors.spec.ts
> +Copyright 2022 The Matrix.org Foundation C.I.C.
Changed to 2023

2023-09-19 14:50 UTC, finsterwalder commented
Any progress on this?
Is there still something missing?

2023-09-20 06:59 UTC, t3chguy commented
![image](https://github.com/matrix-org/matrix-js-sdk/assets/2403652/e2524770-9cc3-4ce8-bede-af2ac5ab7a92)

in future please request re-review if you have made the requested changes otherwise the reviewer may not be notified.

2023-09-20 07:26 UTC, finsterwalder commented
Oh, thanks for the hint. I don't know all those tricks in Github... :-)

2023-09-20 16:44 UTC, t3chguy approved these changes
Looks sane, thanks

2023-09-20 17:01 UTC, merged