Fix reemitter not being correctly wired on user objects created in storage classes
matrix-org/matrix-js-sdk pull request #3796
Opened 2023-10-12 12:44 UTC by MidhunSureshR

Storage classes - `memory.ts` and `indexeddb.ts` both create user objects without setting it up to emit events on matrix client.
This is sometimes preventing the memberlist from updating on incoming presence events because [this listener](https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/rooms/MemberList.tsx#L152) never runs.

2023-10-17 12:49 UTC, MidhunSureshR commented on src/store/index.ts
> +    setUserCreator(creator: UserCreator): void;
Temporary solution until we fix https://github.com/vector-im/element-web/issues/26383

2023-10-17 12:50 UTC, MidhunSureshR reviewed
.

2023-10-23 06:14 UTC, germain-gg requested changes
Thank you for opening this up!
A few things I believe should be updated

2023-10-23 06:14 UTC, germain-gg commented on src/models/user.ts
> +    public static withReEmitterOnClient(userId: string, client: MatrixClient): User {
I think we should change the naming. It should not contain `withReEmitter`, but rather describe what it's doing.
The following seems more appropriate to me, and will survive a future refactor where we decide to move away from event emitters

```suggestion
    public static createUser(userId: string, client: MatrixClient): User {
```

2023-10-23 06:14 UTC, germain-gg commented on src/models/user.ts
> +    public static withReEmitterOnClient(userId: string, client: MatrixClient): User {
I would also suggest making the `User` constructor deprecated and commenting there that folks should use `User.createUser` instead to have all the appropriate events set up

<img width="455" alt="Screenshot 2023-10-23 at 07 10 49" src="https://github.com/matrix-org/matrix-js-sdk/assets/769871/a43fe075-0c3e-4698-9ec4-4d71d568d658">

```
     * @deprecated use `User.withReEmitterOnClient`
```

2023-10-27 06:55 UTC, germain-gg approved these changes
Thank you, LGTM

2023-10-27 07:38 UTC, merged