Bump matrix-sdk-crypto-wasm to 3.0.0
matrix-org/matrix-js-sdk pull request #3849
Opened 2023-11-01 11:21 UTC by richvdh

... which changes the API of `bootstrapCrossSigning` a bit.

2023-11-01 11:27 UTC, t3chguy requested changes
CI says no

2023-11-01 15:36 UTC, richvdh commented
> CI says no

And it has a point. Turns out the SDK has introduced a bug: https://github.com/matrix-org/matrix-rust-sdk/issues/2802

2023-11-10 15:43 UTC, richvdh commented
This is now ready for another look.

2023-11-10 16:04 UTC, t3chguy approved these changes

2023-11-10 23:37 UTC, merged