Bump minimum spec version to v1.5
matrix-org/matrix-js-sdk pull request #3970
Opened 2023-12-20 18:54 UTC by richvdh

We only claim to support a year of spec releases, so this should be fine.

2023-12-20 20:05 UTC, turt2live commented
ftr, the js-sdk could probably go as far as v1.6 if it wanted to. By supporting v1.5, there's already a few servers out there which would no longer be supported - going to v1.6 doesn't appear to change that.

2023-12-20 21:24 UTC, richvdh commented
So the reason I went with 1.5 is that 1.6 wasn't released until 14 February 2023. So if we went with 1.6, we wouldn't actually be supporting the spec from a year ago. (We could bump to 1.6 as soon as 14 February 2024 arrives.)

2023-12-20 22:14 UTC, turt2live commented
Ah, the readme says "last 4", which is meant to be roughly 1 year. Considering 1.9 *just* came out though, it's hard to consider it one of the 4 indeed.

2023-12-20 23:13 UTC, t3chguy requested changes
We should also drop any (now dead) code which specifically handles pre-v1.5 - hopefully that includes a lot of the threads workarounds

2023-12-21 10:26 UTC, richvdh commented
> We should also drop any (now dead) code which specifically handles pre-v1.5 - hopefully that includes a lot of the threads workarounds

Agreed, but that can be done later. It's just tech debt. There's no need to block this change on that work.

2023-12-21 10:28 UTC, t3chguy approved these changes
Sure assuming an issue to say such materialises :)

2023-12-21 11:49 UTC, richvdh commented
Issue filed at https://github.com/matrix-org/matrix-js-sdk/issues/3972

2023-12-21 12:09 UTC, richvdh commented
This will need https://github.com/matrix-org/matrix-react-sdk/pull/12081 and https://github.com/element-hq/element-web/pull/26796 to land first.

2023-12-21 12:09 UTC, t3chguy commented
And probably wants to be a major version bump

2024-01-08 13:01 UTC, merged

2024-01-19 15:32 UTC, richvdh commented
For the record: this got reverted in #4014.