fix IndexedDBStore API documentation
matrix-org/matrix-js-sdk pull request #3987
Opened 2024-01-05 20:30 UTC by WebFreak001

Retroactively changes the changelog entry to include since when this change is needed as well, so that other people upgrading the SDK can more easily find what to change.

Fix #3986

Only documentation & error strings have changed so I have not adjusted any tests. A proper integration test would probably be nice, but I didn't have the time to look into how that is setup on this project.

2024-01-24 13:55 UTC, richvdh approved these changes
Thank you!

2024-01-24 13:55 UTC, richvdh commented on CHANGELOG.md
> + * * `IndexedDBStore.startup()` must be called after using it on `sdk.createClient` now.
```suggestion
 * `IndexedDBStore.startup()` must be called after using it on `sdk.createClient` now.
```

2024-01-24 13:58 UTC, WebFreak001 commented
um it looks like the changelog diff broke just now when I used the github edit feature - is there inconsistent line endings in the file causing the web editor diff to break?

2024-01-24 14:03 UTC, richvdh commented
> um it looks like the changelog diff broke just now when I used the github edit feature - is there inconsistent line endings in the file causing the web editor diff to break?

possibly. Not sure, I'm afraid

2024-01-24 14:21 UTC, WebFreak001 commented
I just removed the changelog entry now, seems to be too much of a hassle to get the line endings right with git

2024-01-24 14:29 UTC, richvdh commented
> I just removed the changelog entry now, seems to be too much of a hassle to get the line endings right with git 

Wasn't the whole point of this PR to update the changelog?

> (also there doesn't seem to be a "unreleased" version where I would need to put the new entry for the upcoming version)

Take a look at the contributing doc. The changelog is autogenerated.

2024-01-24 14:33 UTC, WebFreak001 commented
ah you are right sorry, I forgot what I actually did in this PR - I readded the changelog entry to the version where I put it earlier in the PR

2024-01-24 14:52 UTC, richvdh requested changes
Thanks! A couple of final things, I'm afraid.

* It's failing CI due to a failure from the linter. It's probably complaining about line length, though I haven't checked in detail. Please either see what the matter with it is or run the changes through `prettier`.
* We require sign-off for all changes, even ones as simple as this. Sorry! Please take a look at https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md#sign-off and if you are happy, add a "Signed-off-by" line to the PR description.

2024-01-24 15:00 UTC, WebFreak001 commented
ok should be good now

2024-01-24 15:47 UTC, richvdh commented
Sorry, but as the contributing guide says, I'm afraid we don't accept contributions signed off under a pseudonym, so we'll need your real name to be able to accept this. See https://github.com/element-hq/element-web/blob/develop/CONTRIBUTING.md#private-sign-off.

2024-01-25 09:42 UTC, richvdh approved these changes
Thank you for your patience!

2024-01-25 10:10 UTC, merged