Add event with m.reference relation to unknown parent to the timeline.
matrix-org/matrix-js-sdk pull request #4084
Opened 2024-02-26 06:30 UTC by maheichyk

## Checklist

-   [ ] Tests written for new code (and old code if feasible)
-   [ ] Linter and other CI checks pass
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md))

2024-02-26 06:52 UTC, maheichyk commented
@dbkr, @robintown I somehow cannot add a label (adding `Type: defect` to the PR description and I think it was working before to me) but all other checks are passing, please review.

2024-02-26 13:19 UTC, dbkr requested changes

2024-02-26 13:19 UTC, dbkr commented on src/models/room.ts
> +        if (!parentEventId || !!event.replyEventId || event.getRelation()?.rel_type === "m.reference") {
I'm not sure I really see why an `m.reference` relation needs special treatment here: doesn't the logic apply to any relation that's not a thread (or possibly reply?) relation? Seems like any event with a kind of relation we don't know about, we should assume lives in the main thread? That said, I'd appreciate a second pair of eyes on this before actually suggesting this.

Also, the comment above (apart from having half a sentence) explains both clauses in the if condition, so if you add another, please update the comment to reflect it.

2024-02-27 15:11 UTC, dbkr commented on src/models/room.ts
> +        if (!parentEventId || !!event.replyEventId || event.getRelation()?.rel_type === "m.reference") {
At the moment I'm more inclined to go with the other PR, which seems broadly sensible. The more I think about this, the more I think that actually there's no way we can legitimately say events live in any timeline if we don't know about their parent, so what we should actually be doing is keeping them in a holding area somewhere until we can fetch their parent. That or use https://github.com/matrix-org/matrix-spec-proposals/pull/4023

2024-03-08 15:50 UTC, maheichyk commented
The main problem in relation to the widgets was resolved by another PR to matrix-react-sdk, although would be nice to have these events in the timeline to be shown by Element and not to have a special handling for the widgets.

2024-03-08 15:50 UTC, closed without merging

2024-03-08 15:51 UTC, t3chguy commented
@maheichyk a very related issue is tracked in https://github.com/element-hq/element-web/issues/27132

2024-03-08 16:43 UTC, maheichyk commented
> @maheichyk a very related issue is tracked in [element-hq/element-web#27132](https://github.com/element-hq/element-web/issues/27132)

Yes, it is the same issue to me: event (with custom relation type) is ignored because the parent event is missing (not loaded yet) in the timeline. In our widget case I could see our custom events in the timeline when they are added by the widget with devtools, but when Element is reloaded I could not see any of those. I though that it was a synapse issue, but it was not, all widgets events could be loaded fine via relation to this parent event.

2024-03-08 16:46 UTC, t3chguy commented
Its a tricky topic, the spec doesn't clearly outline how non-standard relations should interact with threads, and getting this wrong means stuck notifications due to the client & server treating those events as contained in different timelines. Ideally the client would be told which thread/main timeline the event belongs to deterministically (either top level thread_id or a value in unsigned) https://github.com/matrix-org/matrix-spec-proposals/pull/4023 would be such a solution