Remove the compare function from utils
matrix-org/matrix-js-sdk pull request #4315
Opened 2024-07-16 11:32 UTC by dbkr

and change the one use of it to just intantiate a collator and use it.

This was marked as internal module so this shouldn't be a breaking change. Of course, react-sdk was using it.

Requires: https://github.com/matrix-org/matrix-react-sdk/pull/12782

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md)).

2024-07-16 12:14 UTC, t3chguy requested changes
The singular collator choice was done to fix a performance issue, please prove that this does not regress that via some performance test comparisons

See https://github.com/matrix-org/matrix-js-sdk/commit/f708c473851093a149de669e49e67ead6d18e553

2024-07-16 17:18 UTC, dbkr commented
New test passes in somewhere around 80ms on my machine, same as with the old code, so instantiating another collator for each sort operation doesn't appear to materially affect things.

2024-07-16 17:24 UTC, t3chguy commented
@dbkr worth testing in browsers, given that is where the performance issue was

2024-07-16 17:24 UTC, t3chguy requested changes
See comment

2024-07-17 08:44 UTC, dbkr commented
Tested on my big(ish) test account - no measurable difference between develop and this PR.

2024-07-17 08:52 UTC, t3chguy approved these changes

2024-07-17 14:34 UTC, merged