Switch sliding sync support to simplified sliding sync
matrix-org/matrix-js-sdk pull request #4400
Opened 2024-09-12 13:38 UTC by dbkr

Experimental PR to test js-sdk with simlified sliding sync.

This does not maintain support for regulaer sliding sync.

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md)).

2024-09-13 17:47 UTC, DoM1niC commented
@dbkr loading DMs names are fixed for me but Avatars don't load inital only when I click on a DM (Room) and the Timeline shows only one recent Message, like this 
![image](https://github.com/user-attachments/assets/0396b65d-9a48-40b1-bead-e5f1428eab29)
after I reopen the Room the History will partially load....

2025-02-20 11:28 UTC, andybalaam approved these changes
Looks good from a Crypto point of view.

2025-02-20 11:55 UTC, richvdh requested changes

2025-02-20 11:55 UTC, richvdh commented on src/common-crypto/CryptoBackend.ts
> +     * Mark all tracked user's device lists as dirty.
```suggestion
     * Mark all tracked users' device lists as dirty.
```

2025-02-20 11:55 UTC, richvdh commented on src/common-crypto/CryptoBackend.ts
> +     * This method will cause additional /keys/query requests on the server, so should be used only
```suggestion
     * This method will cause additional `/keys/query` requests on the server, so should be used only
```

2025-02-20 11:55 UTC, richvdh commented on src/crypto-api/index.ts
> +    markAllTrackedUsersAsDirty(): Promise<void>;
Are you sure this needs exposing to the application? If so, could you share some guidance on when an application should call it? Also, could you have a look through the whole of `CryptoApi` and see if there isn't a better place it fits in the order of methods?

2025-02-20 11:55 UTC, richvdh commented on src/models/room-summary.ts
> +export interface IRoomSummaryMSC4186 {
interfaces shouldn't start with I

2025-02-20 11:55 UTC, richvdh commented on src/models/room-summary.ts
> +export interface IRoomSummaryMSC4186 {
As usual, this needs documentation; particularly so in this case given it is part of js-sdk's public API

2025-02-20 11:55 UTC, richvdh commented on src/models/room-summary.ts
> +import type { Hero } from "./room.ts";
feels like `Hero` should probably come and live in this file, to avoid a reference cycle.

2025-02-20 11:55 UTC, richvdh commented on src/models/room.ts
> +            // use first hero which exists
exists?

2025-02-20 11:55 UTC, richvdh commented on src/models/room.ts
> +export type Hero = {
this needs a doc-comment. The existing `//` comment might provide some inspiration, but it looks like it contains a lot of js-sdk-internal notes which don't really belong in the public API.

2025-02-20 11:55 UTC, richvdh commented on src/models/room.ts
> +// never be set and hence we will always do getMember lookups (at the right time as well).
A bunch of this commentary actually belongs where we do the lookup in `.heroes`.

2025-02-20 11:55 UTC, richvdh commented on src/models/room.ts
> +                }
this logic feels broken.

If we have a SSSS hero who *hasn't* set a displayname or avatar, then we use `this.getMember()`. Isn't that path meant to be used only for the legacy-hero-path?

2025-02-20 11:55 UTC, richvdh commented on src/models/room.ts
> +                    // attempt to look up renderable fields from the m.room.member event if it exists
why do we check if the user is a member of the room in this case, but not in the case that `hero.displayName` or `hero.avatarUrl` have been set?

2025-02-20 11:55 UTC, richvdh commented on src/models/room.ts
> +        });
mild suggestion for clarity

```suggestion
        const heroes = summary["m.heroes"]?.map(
            (h) => (typeof h === "string") ? { userId: h } : h
        );
```

2025-02-20 11:55 UTC, richvdh commented on src/models/room.ts
> +        summary["m.heroes"] = heroes?.map((h) => h.userId);
```suggestion
        // Convert back to the legacy heroes format for the `RoomEvent.Summary` event.
        summary["m.heroes"] = heroes?.map((h) => h.userId);
```

2025-02-20 11:55 UTC, richvdh commented on src/models/room.ts
> +        summary["m.heroes"] = heroes?.map((h) => h.userId);
can't help but feel that modifying the passed-in object in this way is bad karma that will surprise someone in future. Maybe we should document this behaviour in the doc-comment?

2025-02-20 11:55 UTC, richvdh commented on src/models/room.ts
> +                }
could do with a comment here: what is this for?

2025-02-20 11:55 UTC, richvdh commented on src/rust-crypto/rust-crypto.ts
> +     */
note that `RustCrypto` has a "CryptoApi implementation" section, which isn't here. Though, as previously noted, I don't think this actually belongs in `CryptoApi`.

2025-02-20 11:55 UTC, richvdh commented on src/sliding-sync-sdk.ts
> +        logger.log(`onRoomData ${roomId} took ${new Date().getTime() - start}ms`);
feels like these logging changes could do with being a separate PR

2025-02-20 11:55 UTC, richvdh commented on src/sliding-sync.ts
> +}
documentation please. How does this differ from the other `Hero`?

2025-02-20 11:55 UTC, richvdh commented on src/sliding-sync.ts
> +    avatar_url: string;
How can you be sure that these fields will be present?

2025-03-06 13:50 UTC, dbkr commented on src/crypto-api/index.ts
> +    markAllTrackedUsersAsDirty(): Promise<void>;
Seems like it only needed to be in `SyncCryptoCallbacks` which it already was - removed.

2025-03-06 16:45 UTC, dbkr commented on src/models/room.ts
> +            // use first hero which exists
mm, have tried to clarify based on what it appears to be doing

2025-03-06 16:54 UTC, dbkr commented on src/models/room.ts
> +export type Hero = {
Mmm, have kept the tsdoc fairly lightweight and moved the detail into room.ts

2025-03-06 16:58 UTC, dbkr commented on src/models/room.ts
> +// never be set and hence we will always do getMember lookups (at the right time as well).
yeah, it kinda does - have moved the latter half there.

2025-03-07 13:48 UTC, dbkr commented on src/models/room.ts
> +                    // attempt to look up renderable fields from the m.room.member event if it exists
I asked Kegan and it sounds is intentional if the server doesn't populate either field, it will essentially fall back to the old behaviour:

> If we have a Hero then the server has explicitly sent data back and we should use it. But, in the case of where there is no actual data for this hero (avatar/display name) then rather than send nothing we fallback to the m.room.member event's displayname/avatar_url if they exist, as it might have some data, which is better than displaying nothing. So effectively the codepath for v2 fallback because-there-is-no-Hero and SSS-Hero-has-no-data is the same

I've tweaked the comment a bit to reflect this.

2025-03-07 13:57 UTC, dbkr commented on src/models/room.ts
> +                }
I asked Kegan and it sounds is intentional if the server doesn't populate either field, it will essentially fall back to the old behaviour:

> If we have a Hero then the server has explicitly sent data back and we should use it. But, in the case of where there is no actual data for this hero (avatar/display name) then rather than send nothing we fallback to the m.room.member event's displayname/avatar_url if they exist, as it might have some data, which is better than displaying nothing. So effectively the codepath for v2 fallback because-there-is-no-Hero and SSS-Hero-has-no-data is the same

I've tweaked the comment a bit to reflect this.

2025-03-07 14:03 UTC, dbkr commented on src/models/room.ts
> +                    // attempt to look up renderable fields from the m.room.member event if it exists
Oh, as in should it still ensure that the user is definitely in the room even if all the information comes from the hero object?

2025-03-07 15:01 UTC, dbkr commented on src/models/room.ts
> +                }
done in 8a26967f5

2025-03-07 15:01 UTC, dbkr commented on src/rust-crypto/rust-crypto.ts
> +     */
yep, it's gone.

2025-03-07 15:04 UTC, dbkr commented on src/sliding-sync-sdk.ts
> +        logger.log(`onRoomData ${roomId} took ${new Date().getTime() - start}ms`);
Mmm, they do seem a bit unrelated - gone.

2025-03-07 15:18 UTC, dbkr commented on src/sliding-sync.ts
> +}
Done in 7028a88b2

2025-03-07 15:19 UTC, dbkr commented on src/sliding-sync.ts
> +}
Done in 7028a88b2

2025-03-07 15:21 UTC, dbkr commented on src/sliding-sync.ts
> +}
Done in 7028a88b2

2025-03-07 15:21 UTC, dbkr commented on src/sliding-sync.ts
> +    avatar_url: string;
Mm, not sure why these weren't optional since the code was good about checking their existence. Fixed.

2025-03-12 12:07 UTC, richvdh requested changes

2025-03-12 12:07 UTC, richvdh commented on src/models/room.ts
> +                // mode these fields will never be set and hence we will always do getMember lookups (at the right time as well).
hrm, that's not the same thing as kegan said, apparently:

> But, in the case of where there is no actual data for this hero (avatar/display name) then rather than send nothing we fallback to the m.room.member event's displayname/avatar_url if they exist, as it might have some data, which is better than displaying nothing

I don't really understand why the server would return no avatar/displayname when the hero has set them. Is this to work around a server bug?

2025-03-12 12:07 UTC, richvdh commented on src/models/room.ts
> +                }
I don't really understand, but let's take it to another thread.

2025-03-12 12:07 UTC, richvdh commented on src/models/room.ts
> +     * in the `RoomEvent.Summary` event.
this buries the lede

```suggestion
     * Note that the provided `summary` will be modified. (Specifically, it will be converted to a legacy-style 
     * `IRoomSummary`).
```

2025-03-13 09:23 UTC, dbkr commented on src/models/room.ts
> +    // It is used in MSC4186 (Simplified Sliding Sync) as a replacement for the old 'summary' field.
Yeah, that matches my understanding.

2025-03-13 14:22 UTC, kegsay commented on src/models/room.ts
> +                // mode these fields will never be set and hence we will always do getMember lookups (at the right time as well).
There isn't a specific server bug here, it's primarily to avoid showing user IDs / no avatars if we can help it. The proxy would map `m.room.member` events to the `Hero` structs so they _should_ always be in sync. If they are out of sync, it will be either:
 - the Hero is blank but the member event on the client has data.
 - The member event on the client is blank and the Hero has data.

The code we're talking about is for the first point, which I think can only happen if:
 - Alice has a name/avatar set.
 - Bob goes offline for ages.
 - Alice unsets her name/avatar.
 - Bob comes back online, and is sent Alice as a Hero with no name/avatar.
 - Bob uses the old values.

..which is probably not what we want here, so happy for us to always use the Hero values and not fallback in SSS mode.

2025-03-13 14:25 UTC, dbkr commented on src/models/room.ts
> +                // mode these fields will never be set and hence we will always do getMember lookups (at the right time as well).
I can go make it do that then

2025-03-14 12:50 UTC, dbkr commented on src/models/room.ts
> +                // mode these fields will never be set and hence we will always do getMember lookups (at the right time as well).
OK, I've had a go at this in 7506df233, although it does mean explicitly tracking where the hero came from so I'm not 100% sure I've interpreted this correctly, but easiest to show in an actual diff than try to explain. If so, I think most of the rest of the feedback is fixed too.

2025-03-14 12:53 UTC, dbkr commented on src/models/room.ts
> +                // mode these fields will never be set and hence we will always do getMember lookups (at the right time as well).
Oh wait no, this doesn't work at all because the same type is used in the RoomSummaryMSC4186 type

2025-03-14 14:28 UTC, dbkr commented on src/sliding-sync.ts
>  }
I've added a field to one of them too in order to track the difference. We could extend, but if we have to map then I guess we may as well have two distinct types? No strong opinion though., I have linked between the two, albeit not with proper `@link` because it doesn't work without importing the type which gets flagged as an unused import.

2025-03-14 14:29 UTC, dbkr commented on src/models/room.ts
> +                // mode these fields will never be set and hence we will always do getMember lookups (at the right time as well).
Right, now updated again, splitting he setSummary method in two to avoid having to fake up an object to make it look like the old format which makes one of the types unnecessary.

2025-03-18 13:28 UTC, richvdh approved these changes
A few nits but generally lgtm

2025-03-18 13:28 UTC, richvdh commented on src/models/room-summary.ts
> +     * have been set by the server if available. If false, these fields will always be undefined.
```suggestion
     * have been set by the server if available. If false, the `Hero` has been constructed from a `/v3/sync` response,
     * so these fields will always be undefined.
```

2025-03-18 13:28 UTC, richvdh commented on src/models/room.ts
> +                // mode these fields will never be set and hence we will always do getMember lookups (at the right time as well).
looks sensible to me now.

2025-03-18 13:28 UTC, richvdh commented on src/models/room.ts
> +     * @param invitedCount
:-1:

2025-03-18 13:28 UTC, richvdh commented on src/models/room.ts
>          // get members that are NOT ourselves and are actually in the room.
this comment looks outdated -- we no longer check if heros are in the room

2025-03-18 13:28 UTC, richvdh commented on src/models/room.ts
>              // if we have a summary, the member state events should be in the room state
this comment feels like it's got a bit lost, as well

2025-03-18 15:09 UTC, dbkr commented on src/models/room.ts
> +        if (invitedCount !== undefined && Number.isInteger(invitedCount)) {
Typescript complains without these checks as Number.isInteger doesn't accept `undefined` for whatever reason.

2025-03-18 15:16 UTC, dbkr commented on src/models/room.ts
>              // if we have a summary, the member state events should be in the room state
Mmm yeah, should be better now.

2025-03-18 17:23 UTC, dbkr commented
Force merging because the upstream will be incompatible

2025-03-18 17:23 UTC, merged