Move out `crypto/aes`
matrix-org/matrix-js-sdk pull request #4431
Opened 2024-09-25 13:17 UTC by florianduros

## Checklist

-   [ ] Tests written for new code (and old code if feasible).
-   [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
-   [ ] Linter and other CI checks pass.
-   [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md)).

2024-09-27 10:07 UTC, richvdh requested changes
looks like the right direction! A few suggestions for improvements.

2024-09-27 10:07 UTC, richvdh commented on src/utils/encryptAES.ts
> +export async function encryptAES(
Given the objective of the `utils` hierarchy (to expose small modules that have only a single piece of functionality), I think we should use default exports here (and for `decryptAES`), with

```
export default async function ...
```

(Obviously, you'll have to update all the imports from `import { encryptAES } from ...` to `import encryptAES from ...`.)

2024-09-27 10:07 UTC, richvdh commented on src/utils/decryptAES.ts
> +export async function decryptAES(data: SecretEncryptedPayload, key: Uint8Array, name: string): Promise<string> {
Also, rename the file, of course.

2024-09-27 10:07 UTC, richvdh commented on src/utils/decryptAES.ts
> + * @param data - the encrypted data, returned by {@link encryptAES}.
These links don't work. Try something like:

```suggestion
@param data - the encrypted data, returned by {@link utils/encryptAES.default | encryptAES}.
```

(Assuming you're using default exports.)

2024-09-27 10:09 UTC, florianduros commented on src/utils/@types/SecretEncryptedPayload.ts
we will importing all the types when we import `AESEncryptedSecretStoragePayload`.

2024-09-27 10:12 UTC, richvdh commented on src/utils/@types/SecretEncryptedPayload.ts
That's probably ok though? They are only typescript types, there is no runtime cost.

2024-09-30 16:27 UTC, richvdh approved these changes
https://github.com/matrix-org/matrix-js-sdk/pull/4431#discussion_r1778314286 seems to have got lost.

LGTM otherwise

2024-10-01 14:08 UTC, merged