Device Dehydration | js-sdk: store/load dehydration key
matrix-org/matrix-js-sdk pull request #4599
Opened 2024-12-26 16:06 UTC by BillCarsonFr

Fixes https://github.com/matrix-org/matrix-js-sdk/issues/4483

Draft because depends on rust-sdk: https://github.com/matrix-org/matrix-rust-sdk/pull/4399 and needs new wasm bindings version.

Added basic support to cache created keys and read from store instead of in memory.
Then adding some basic signalling to DeviceDehydrationManager, helpfull for tests and also for apps to have some feedbacks on device rehydration (reports progress for example)

## Checklist

- [ ] Tests written for new code (and old code if feasible).
- [ ] New or updated `public`/`exported` symbols have accurate [TSDoc](https://tsdoc.org/) documentation.
- [ ] Linter and other CI checks pass.
- [ ] Sign-off given on the changes (see [CONTRIBUTING.md](https://github.com/matrix-org/matrix-js-sdk/blob/develop/CONTRIBUTING.md)).

2025-01-02 23:35 UTC, uhoreg reviewed
I only did a quick review because the the compiler errors are distracting

2025-01-02 23:35 UTC, uhoreg commented on src/rust-crypto/DehydratedDeviceManager.ts
> +                const key = RustSdkCryptoJs.DehydratedDeviceKey.createKeyFromArray(bytes);
`bytes` should be zeroed out after this line, to avoid keeping the key in memory

2025-01-02 23:35 UTC, uhoreg commented on src/rust-crypto/DehydratedDeviceManager.ts
> +        const key = (await this.getCachedKey()) || (await this.getKey(false));
Why is `getCachedKey` called, when `getKey` already calls `getCachedKey` and returns its value if it's non-empty?

2025-01-09 21:10 UTC, uhoreg commented on src/rust-crypto/DehydratedDeviceManager.ts
> +        const key = ((await this.getCachedKey()) || (await this.getKey(true)))!;
```suggestion
        const key = (await this.getKey(true))!;
```
since `getKey` already calls `getCachedKey`

2025-01-10 01:49 UTC, uhoreg commented on src/crypto-api/index.ts
> +export abstract class DehydratedDevicesAPI extends TypedEventEmitter<
The class and methods need documentation.

2025-01-10 02:03 UTC, uhoreg commented on spec/integ/crypto/device-dehydration.spec.ts
> +        const dehydratedDevices = matrixClient.getCrypto()!.dehydratedDevices();
It might be better to have the crypto object re-emit the dehydration events, rather than exposing the dehydration manager object.

2025-01-15 11:51 UTC, richvdh commented
> Draft because depends on rust-sdk: https://github.com/matrix-org/matrix-rust-sdk/pull/4399 and needs new wasm bindings version.

This is no longer the case, I think? Can we update the description?

2025-01-16 10:06 UTC, andybalaam approved these changes
Looks reasonable to me, but definitely needs review from people who are closer to the dehydrated devices design.

2025-01-17 17:44 UTC, richvdh requested changes

2025-01-17 17:44 UTC, richvdh commented on src/crypto-api/index.ts
> +export enum DehydratedDevicesEvents {
doc-comment here, please. What does this enum represent?

2025-01-17 17:44 UTC, richvdh commented on src/crypto-api/index.ts
> +export type DehydratedDevicesEventsMap = {
this needs a doc-comment too, if it's being exported. (Does it really need to be?)

2025-01-17 17:44 UTC, richvdh commented on src/crypto-api/index.ts
> +}
suggest putting all this stuff in a separate file within `crypto-api`, like we've done with the other stuff below.

2025-01-17 17:44 UTC, richvdh commented on src/crypto-api/index.ts
> +export enum DehydratedDevicesEvents {
Also, consider whether this really needs to be separate from `CryptoEvent`.

2025-01-17 17:44 UTC, richvdh commented on spec/integ/crypto/device-dehydration.spec.ts
> +        const dehydratedDevices = matrixClient.getCrypto()!.dehydratedDevices();
+1 to this. Otherwise there is redundancy in the API, between `crypto.dehydratedDevices().start()` and `crypto.startDehydration()`: which one am I supposed to use, as a user of the library?

(You'll also need to have `MatrixClient` re-emit them in `initRustCrypto`, since `CryptoApi` itself is not an event emitter, and give them better names that reflect the fact they are to do with dehydration.)

Basically, do the same thing we've done with `KeyBackupStatus` etc.

2025-01-17 17:44 UTC, richvdh commented on src/crypto-api/index.ts
> +    RehydrationProgress = "RehydrationProgress",
this needs better documentation on what the payload of the event is.

```suggestion
    /**
      * Emitted during rehydration, to inform the application of rehydration progress.
      *
      * The payload is a pair `[roomKeyCount: number, toDeviceCount: number]`, where
      * `roomKeyCount` is (what, exactly??) and ``toDeviceCount` is (something else??
      */
    RehydrationProgress = "RehydrationProgress",
```

2025-01-22 02:04 UTC, uhoreg commented on src/crypto-api/index.ts
> +}
I followed the example of key backups (src/rust-crypto/backup.ts), and moved the events to crypto-api/CryptoEvent.ts, and the event map to src/rust-crypto/DehydratedDeviceManager.ts.  But I can move them elsewhere if there's some place better.

2025-01-22 02:07 UTC, uhoreg commented
I think that I've addressed all of @richvdh 's comments.

(Of course, this can't be merged until https://github.com/matrix-org/matrix-js-sdk/issues/4634 is fixed)

2025-01-22 08:55 UTC, florianduros approved these changes

2025-01-22 10:59 UTC, richvdh commented on src/crypto-api/CryptoEventHandlerMap.ts
> +import { DehydratedDevicesEventMap } from "../rust-crypto/DehydratedDeviceManager.ts";
`crypto-api` really shouldn't be pulling things in from `rust-crypto`. `RustBackupCryptoEventMap` is setting a poor example here.

I think the right way to do this is to add the values from `DehydratedDevicesEventMap` to `CryptoEventHandlerMap`, and then redefine `DehydratedDevicesEventMap` as `Pick<CryptoEventHandlerMap, DehydratedDevicesEvents>` or something like that.

2025-01-22 10:59 UTC, richvdh commented on src/rust-crypto/DehydratedDeviceManager.ts
> +     * Implementation of {@link DehydratedDevicesAPI#isSupported}.
`DehydratedDevicesAPI` no longer exists

2025-01-22 10:59 UTC, richvdh commented on src/rust-crypto/DehydratedDeviceManager.ts
> +     * Implementation of {@link DehydratedDevicesAPI#start}.
ditto

2025-01-22 10:59 UTC, richvdh commented on src/crypto-api/CryptoEvent.ts
> +    DehydrationSchedulingError = "dehydration.DehydrationSchedulingError",
It would be good if, for each event, we could give a quick one-sentence summary of roughly when we expect them to happen, in the course of an application's lifecycle (or if there is a specific API call that causes them to fire?).

Also, if there's anything specific we might expect the application to do with the events?

2025-01-22 10:59 UTC, richvdh commented on src/crypto-api/CryptoEvent.ts
> +    /** Fires when a dehydrated device key has been cached */
could you explain what "cached" means (stored in the local database? In memory?)

2025-01-22 10:59 UTC, richvdh commented on src/crypto-api/CryptoEvent.ts
> +    DehydrationSchedulingError = "dehydration.DehydrationSchedulingError",
to a naive reader, "rotation" and "scheduling" sound like different things. Shouldn't this be called `DehydrationDeviceRotationError` ?

2025-01-22 10:59 UTC, richvdh commented on src/crypto-api/CryptoEvent.ts
> +    RehydrationEnded = "dehydration.RehydrationEnded",
maybe list this after `RehydrationProgress`?

Presumably it indicates that rehydration *successfully* completed? Maybe say so in the comment?

Also `RehydrationCompleted` might be a better name?

2025-01-22 10:59 UTC, richvdh commented on src/rust-crypto/DehydratedDeviceManager.ts
> +        if (!cachedKey) {
suggest an early return here, to avoid two calls to `getCachedKey` and dodgy `!` operators

```suggestion
        const cachedKey = await this.getCachedKey();
        if (cachedKey) return cachedKey;
```

(can we then inline `getCachedKey`?)

2025-01-22 11:04 UTC, richvdh commented on src/rust-crypto/DehydratedDeviceManager.ts
> +export type DehydratedDevicesEvents =
does this need to be `exported`? It doesn't seem to be used elsewhere?

(Alternatively, maybe import it to `rust-crypto.ts` and use it to help with the re-emits)

2025-01-24 14:45 UTC, uhoreg commented
SonarCloud says I need to add more tests, but should be ready for re-review otherwise

2025-01-27 12:57 UTC, richvdh approved these changes
A few nits, but LGTM.

And yes, looks like we need a test for loading the key from 4S?

2025-01-27 12:57 UTC, richvdh commented on src/crypto-api/CryptoEvent.ts
> +     * before `startDehydration` returns. */
nit
```suggestion
     * before `startDehydration` returns.
     */
```

2025-01-27 12:57 UTC, richvdh commented on src/rust-crypto/DehydratedDeviceManager.ts
> +export type DehydratedDevicesEventMap = Pick<CryptoEventHandlerMap, DehydratedDevicesEvents>;
nit: does this need to be `export`ed?

```suggestion
type DehydratedDevicesEventMap = Pick<CryptoEventHandlerMap, DehydratedDevicesEvents>;
```

2025-01-27 12:57 UTC, richvdh commented on src/rust-crypto/DehydratedDeviceManager.ts
>       * Creates a new key and stores it in secret storage.
```suggestion
     * Creates a new key and stores it in secret storage.
     *
     * @returns The newly-generated key.
```

2025-01-27 12:57 UTC, richvdh commented on src/rust-crypto/DehydratedDeviceManager.ts
>          }
If you're going to do early returns, might as well take benefit from them

```suggestion

        // We successfully found the key in secret storage: decode it, and cache it in
        // the rust SDK's crypto store.
        const bytes = decodeBase64(keyB64);
        try {
            const key = RustSdkCryptoJs.DehydratedDeviceKey.createKeyFromArray(bytes);
            await this.cacheKey(key);
            return key;
        } finally {
            bytes.fill(0);
        }
```

2025-01-27 12:57 UTC, richvdh commented on src/rust-crypto/DehydratedDeviceManager.ts
>          }
.oO (if we're going to `.fill(0)` on `bytes`, shouldn't we also do so for `keyB64` ?)

2025-01-27 17:40 UTC, uhoreg commented on src/rust-crypto/DehydratedDeviceManager.ts
>          }
> .oO (if we're going to `.fill(0)` on `bytes`, shouldn't we also do so for `keyB64` ?)

Ideally we should, but keyB64 is a string and I don't think we can modify a string?

2025-01-27 17:51 UTC, richvdh commented on src/rust-crypto/DehydratedDeviceManager.ts
>          }
true

2025-01-27 22:19 UTC, merged